name: "Check conventional commits"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "*/develop/*"
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Please look up the latest version from
      # https://github.com/amannn/action-semantic-pull-request/releases
      - uses: amannn/action-semantic-pull-request@v3.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            # Configure which types are allowed.
            # Default: https://github.com/commitizen/conventional-commit-types
            types: |
              feat
              fix
              perf
              revert
              docs
              chore
              refactor
              ci
            # When using "Squash and merge" on a PR with only one commit, GitHub
            # will suggest using that commit message instead of the PR title for the
            # merge commit, and it's easy to commit this by mistake. Enable this option
            # to also validate the commit message for one commit PRs.
            validateSingleCommit: true
